name: Build Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*"

jobs:
  build_wheel:
    name: Build pp39-manylinux_i686 Wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install correct numpy version
        run: python -m pip install "numpy==2.0.2"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.20

      - name: Build Wheel
        run: cibuildwheel --output-dir wheelhouse --only pp39-manylinux_i686

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: pp39-manylinux_i686-wheel
          path: wheelhouse/*.whl
